### ISSUE TITLE
humann utility

### ISSUE THREAD

**Issue by jflucier** [jflucier/ILL_pipelines#4]
while you're at it, the operation at [this line](https://github.com/biobakery/humann#humann_split_stratified_table) can actually be done using a humann utility, namely [this one](https://github.com/biobakery/humann#humann_split_stratified_table). It takes the .tsv created by the humann_regroup script loop and splits them exactly like I want (stratified levels + community level, called "unstratified" here)

_Originally posted by @jorondo1 in https://github.com/jflucier/ILL_pipelines/issues/3#issuecomment-1098416331_

**Comment by jflucier** [comment]
links dont seem to work.

tou mean this [line 107](https://github.com/jflucier/ILL_pipelines/blob/886be7ab3954bb8ef7c58db977bd17eb713d3078/humann_custom/03_humann_custom_run.sh#L107) can be removed from loop

After loop we add this line of code:

`
humann_split_stratified_table \
--input $SLURM_TMPDIR/${__sample}/${__sample}_genefamilies.tsv \
--output $SLURM_TMPDIR/${__sample}/ \


`

is this what you want?

**Comment by jorondo1** [comment]
oh nope sorry wrong link

i wrote [lines 119-126](https://github.com/jflucier/ILL_pipelines/blob/886be7ab3954bb8ef7c58db977bd17eb713d3078/humann_custom/03_humann_custom_run.sh#L119-L126) manually, but then discovered the split stratified table would do exactly that but also split the tables which is slightly better (and maybe less error-prone!)

basically apply this to all the *.tsv files (i think it automatically renames both outputs)

the idea is basically splitting the file because it contains redundant information ; read counts for the community level (unstratified) and read counts for every taxa (stratified)

**Comment by jflucier** [comment]
ok then we modify [lines 119-126](https://github.com/jflucier/ILL_pipelines/blob/886be7ab3954bb8ef7c58db977bd17eb713d3078/humann_custom/03_humann_custom_run.sh#L119-L126) with 

```
humann_split_stratified_table
--input $SLURM_TMPDIR/${__sample}/${__sample}_genefamilies.tsv
--output $SLURM_TMPDIR/${__sample}/ \

```

is that it?

**Comment by jorondo1** [comment]
je pense bien oui !

**Comment by jflucier** [comment]
good eye!

done. View change [here](https://github.com/jflucier/ILL_pipelines/commit/95c32dae56b6ff2444ee931dda0a9bea4f085671)
